server:
  port: 8081
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/mysdb2
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: 
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: amitk73262@gmail.com
app:
 message:
  dupEmail: Duplicate Email
  regSucc: User Registered
  regFail: registeration Failed
  invaildCredentials: Invalid credentials
  pwdMatchErr: New Pwd and Confirm Pwd Should be same
  pwdUpdateErr: Password update is Failed
  oldPwdErr: Given Old Password is Wrong
